#!/usr/bin/env bash

if [ $1 = "preprocess" ] 
then 
  shift
  python data_preprocess_NEST.py $@
elif [ $1 = "run" ]
then
  shift
  python -u run_NEST.py $@ 
elif [ $1 = "postprocess" ] 
then
  shift
  python output_postprocess_NEST.py $@
elif [ $1 = "visualize" ] 
then
  shift
  python output_visualization_NEST.py $@
elif [ $1 = "interactive" ] 
then
  shift
  cd $1
  shift
  bash nest_interactive $@ 
elif [ $1 = "output_graph_picture" ] 
then
  shift
  bash dot_to_pdf_svg.sh $@
fi

